# Generated by Django 4.1.2 on 2025-05-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('electronica', 'Electrónica'), ('manuales', 'Manuales'), ('plomeria', 'Plomeria'), ('materiales', 'Materiales')], default='hogar', max_length=20),
        ),
    ]
