# Generated by Django 4.1.2 on 2025-05-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('manuales', 'Herramientas manuales'), ('materiales', 'Materiales'), ('electronica', 'Electricidad'), ('plomeria', 'Plomería')], max_length=20),
        ),
    ]
