# Generated by Django 4.2.7 on 2025-05-20 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_orden_itemorden'),
        ('tienda', '0004_alter_producto_categoria'),
    ]

    operations = [
    ]
