# Generated by Django 4.2.7 on 2025-05-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_orden_estado_orden_metodo_pago_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='aceptado_por_vendedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('entregado_a_vendedor', 'Entregado a vendedor'), ('entregado_a_cliente', 'Entregado a cliente'), ('rechazada', 'Rechazada')], default='pendiente', max_length=30),
        ),
    ]
