# Generated by Django 4.2.7 on 2025-05-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_orden_aceptado_por_vendedor_alter_orden_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('entregado_a_vendedor', 'Entregado a vendedor'), ('entregado_a_cliente', 'Entregado a cliente'), ('completado', 'Completado por bodega'), ('validado', 'Validado por contador'), ('rechazada', 'Rechazada')], default='pendiente', max_length=30),
        ),
    ]
