# Generated by Django 5.2.1 on 2025-05-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_orden_fecha_pago_orden_paypal_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('manuales', 'Herramientas manuales'), ('materiales', 'Materiales'), ('electronica', 'Electricidad'), ('plomeria', 'Plomería')], max_length=30),
        ),
    ]
