# Generated by Django 5.2.1 on 2025-05-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='sucursal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('manuales', 'Herramientas manuales'), ('materiales', 'Materiales'), ('electronica', 'Electricidad'), ('plomeria', 'Plomería'), ('construcción', 'Construcción')], max_length=30),
        ),
    ]
