# Generated by Django 5.2.1 on 2025-05-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_orden_direccion_orden_sucursal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('manuales', 'Herramientas manuales'), ('electronica', 'Electricidad'), ('plomeria', 'Plomería'), ('construcción', 'Construcción')], max_length=30),
        ),
    ]
