# Generated by Django 5.2.1 on 2025-05-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('manuales', 'Herramientas manuales'), ('electronica', 'Electricidad'), ('plomeria', 'Plomería'), ('construccion', 'Construccion')], max_length=30),
        ),
    ]
