# Generated by Django 4.2.7 on 2025-06-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_alter_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='verificado_por_contador',
            field=models.BooleanField(default=False),
        ),
    ]
