# Generated by Django 4.2.7 on 2025-06-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_orden_verificado_por_contador'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='ocultar_para_vendedor',
            field=models.BooleanField(default=False),
        ),
    ]
